### ISSUE TITLE
a-zA-Z0-9 keys not working on win11 during prompting

### ISSUE THREAD

**Issue by codesunicorn** [charmbracelet/crush#396]
### Describe the bug

a-zA-Z0-9 keys not working on win11

### Setup

Please complete the following information along with version numbers, if applicable.
 - Windows
 - cmd/ PS ( checked both )

*Note: you might encounter rendering issues if your locale does not use
`UTF-8` encoding. Please check your locale (`locale` on POSIX systems) to
see what encoding is being used by your system.*

### To Reproduce

1. Install via npm, Go to cmd/PS 
2. Start Crush
3.  select a model
4. try to type prompt

**Comment by jdiago-passerelle** [comment]
Same here on win11 with crush v0.1.9. Cannot enter any prompt.

**Comment by andreynering** [comment]
I could not reproduce this at all. Tried on both PowerShell and Command Prompt. I even downloaded the npm release here to be sure, and that one also works fine for me.

As a side note, we just merged a somewhat-related issue, but that affects the `Y` and `N` keys only and only on onboarding. https://github.com/charmbracelet/crush/pull/402

**Comment by bakugo** [comment]
Same problem, on both Windows 10 and 11, with every combination of cmd/PowerShell/Windows Terminal. Can't type anything.

**Comment by jdiago-passerelle** [comment]
v0.1.10 fixed it for me. 
**Edit: Actually I'm not sure it's v0.1.10 but I found when Num Lock is enabled I cannot type anything and when it's disabled I can type a prompt just fine!**

**Comment by nameerakhter** [comment]
yeah same issue for me as well cannot type antyhing

**Comment by andreynering** [comment]
@bakugo @nameerakhter Did you try pressing <kbd>numlock</kbd> like @jdiago-pdata suggested?

**Comment by bakugo** [comment]
Can confirm, the issue only happens with numlock on.

**Comment by beardsciences** [comment]
Confirmed. @bakugo @andreynering this is correct, it's fixed by turning off numlock.

**Comment by aymanbagabas** [comment]
Thank you, @codesunicorn, for reporting this one. This is now fixed in `main` and will be part of next release 🙂

**Comment by codesunicorn** [comment]
unfortunately, my laptop does not even have a numlock key (no dedicated numpad), so cannot check that particular scenario.

btw , i tried this on 0.1.11 , is still not working there.

What works : Shift+Enter, Tab , Ctrl+combination keys,
What doesn't : a-zA-Z0-9 in prompt

**Comment by aymanbagabas** [comment]
> What works : Shift+Enter, Tab , Ctrl+combination keys, What doesn't : a-zA-Z0-9 in prompt

Are you on a specific layout?

**Comment by codesunicorn** [comment]
> > What works : Shift+Enter, Tab , Ctrl+combination keys, What doesn't : a-zA-Z0-9 in prompt
> 
> Are you on a specific layout?

no, eng keyboard but without seperate numpad , like compact laptops.

**Comment by aymanbagabas** [comment]
> no, eng keyboard but without seperate numpad , like compact laptops.

What's the version and build number of Windows are you using? Are you on Windows Terminal? Are you using WSL?
