### ISSUE TITLE
UI Interaction Issues: JetBrains IDEs (IDEA, Goland, etc.) Built-in Terminal Has Sliding and Display Anomalies

### ISSUE THREAD

**Issue by hhrhhrhhr** [charmbracelet/crush#573]
Describe the bug
There are significant UI interaction issues in the built-in terminal of JetBrains IDEs (including IntelliJ IDEA and Goland). Specifically, on macOS systems, the context sliding operation within the terminal is not smooth, and there are UI display abnormalities, which affect the normal user experience.
Setup
Please complete the following information along with version numbers, if applicable.

OS: macOS
Shell: [Please fill in your used Shell here, such as zsh, bash, etc.]
Terminal Emulator: JetBrains IDE built-in terminal
Terminal Multiplexer: [Fill in if used, such as tmux; fill N/A if not used]

Note: you might encounter rendering issues if your locale does not use
UTF-8 encoding. Please check your locale (locale on POSIX systems) to
see what encoding is being used by your system.
To Reproduce

Open JetBrains IDEs (such as IntelliJ IDEA or Goland)
Access the built-in terminal (usually via View > Tool Windows > Terminal)
Execute some commands that generate a lot of output in the terminal (such as viewing long logs, using text editors, etc.)
Try to slide up and down with the mouse or trackpad
Observe that the sliding is not smooth and UI display disorders may occur
Source Code
Since this issue is about the interaction and display of the IDE's built-in terminal, it does not involve specific source code. However, it can be reproduced by running any command that generates a large amount of output in the terminal, for example:

bash
# Generate a lot of text output to test sliding and display
for i in {1..1000}; do echo "Test line $i: This is a text content used to test terminal sliding and display"; done

Expected behavior
It is expected that sliding operations in the built-in terminal of JetBrains IDEs can respond smoothly, and the UI display remains normal without 卡顿，misalignment or other abnormalities, providing an interactive experience similar to the system's native terminal.
Screenshots
[If possible, please add screenshots showing the problem here]
Additional context
Many developers are accustomed to using the IDE's built-in terminal for daily development work. A good terminal interaction experience is crucial for improving work efficiency. Fixing such UI interaction issues will significantly enhance the user experience, and I believe more developers will be willing to use the built-in terminal function of JetBrains IDEs. Thank you to the development team for your attention and fixes, and look forward to your reply!

**Comment by meowgorithm** [comment]
Appreciate the note. This one just hit our radar and it's a priority for us.

We're on it.

**Comment by meowgorithm** [comment]
Hey! This is fixed on `main` and will be available in the next release.

**Comment by hhrhhrhhr** [comment]
> Hey! This is fixed on `main` and will be available in the next release.

hello，I noticed that JetBrains IDEA still has some scrolling issues, although it's better than before—still not smooth enough.
